/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgenciaTurismo.vistas;

import AgenciaTurismo.eventosGlobales.AdapterVentana;
import AgenciaTurismo.vistas.RegistroCliente;
//import AgenciaTurismo.vistas.windowHospedaje;
/**
 *
 * @author USER
 */
public class GuiAgenciaTurismo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAgencia
     */
    public GuiAgenciaTurismo() {
        AdapterVentana adaptadorMain=new AdapterVentana();
        this.addWindowListener(adaptadorMain);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        ReguistroClientes = new javax.swing.JMenuItem();
        MenuReserva = new javax.swing.JMenu();
        ReguistroReserva = new javax.swing.JMenuItem();
        MenuHospedaje = new javax.swing.JMenu();
        ReguistroHospedaje = new javax.swing.JMenuItem();
        MenuPaqueteTuristicos = new javax.swing.JMenu();
        ReguistroPaquetes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        MenuCliente.setText("CLIENTE");

        ReguistroClientes.setText("Registrar");
        ReguistroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroClientesActionPerformed(evt);
            }
        });
        MenuCliente.add(ReguistroClientes);

        jMenuBar1.add(MenuCliente);

        MenuReserva.setText("RESERVA");

        ReguistroReserva.setText("Registrar");
        ReguistroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroReservaActionPerformed(evt);
            }
        });
        MenuReserva.add(ReguistroReserva);

        jMenuBar1.add(MenuReserva);

        MenuHospedaje.setText("HOSPEDAJE");

        ReguistroHospedaje.setText("Registrar");
        ReguistroHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroHospedajeActionPerformed(evt);
            }
        });
        MenuHospedaje.add(ReguistroHospedaje);

        jMenuBar1.add(MenuHospedaje);

        MenuPaqueteTuristicos.setText("PAQUETE TURISTICO");

        ReguistroPaquetes.setText("Registrar");
        ReguistroPaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReguistroPaquetesActionPerformed(evt);
            }
        });
        MenuPaqueteTuristicos.add(ReguistroPaquetes);

        jMenuBar1.add(MenuPaqueteTuristicos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReguistroPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroPaquetesActionPerformed
        // TODO add your handling code here:
        RegistroPaquete reguistro=new RegistroPaquete();
        reguistro.setVisible(true);
    }//GEN-LAST:event_ReguistroPaquetesActionPerformed

    private void ReguistroHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroHospedajeActionPerformed
        // TODO add your handling code here:
        RegistroHospedaje reguistroHospedaje=new RegistroHospedaje();
        reguistroHospedaje.setVisible(true);
    }//GEN-LAST:event_ReguistroHospedajeActionPerformed

    private void ReguistroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroReservaActionPerformed
        // TODO add your handling code here:
       RegistroReserva reguistroReserva=new RegistroReserva();
       reguistroReserva.setVisible(true);
    }//GEN-LAST:event_ReguistroReservaActionPerformed

    private void ReguistroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReguistroClientesActionPerformed
        RegistroCliente reguistroCliente=new RegistroCliente();
        reguistroCliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReguistroClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAgenciaTurismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAgenciaTurismo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuHospedaje;
    private javax.swing.JMenu MenuPaqueteTuristicos;
    private javax.swing.JMenu MenuReserva;
    private javax.swing.JMenuItem ReguistroClientes;
    private javax.swing.JMenuItem ReguistroHospedaje;
    private javax.swing.JMenuItem ReguistroPaquetes;
    private javax.swing.JMenuItem ReguistroReserva;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
